stages:
  - check-style
  - run-test

check:
  stage: check-style
  image: python:3.5
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: run-test
  image: python:3.5
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
