stages:
  - check-style
  - run-test

check:
  stage: check-style
  image: python:3.5.4
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - make clean
    - make setup
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: run-test
  image: python:3.5.4
  services:
    - postgres:9.6
  variables:
    PIP_CACHE_DIR: pip-cache
    ENV: test
    POSTGRES_DB: winterthur_test
    POSTGRES_USER: winterthur
    POSTGRES_PASSWORD: winterthur
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - make setup
  script:
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
